# Generated by Django 5.1.4 on 2025-01-06 20:57

from django.db import migrations

INITIAL_CATEGORIES = {
    "Nieruchomości": {
        "Mieszkania": {
            "Sprzedaż": {},
            "Wynajem": {},
        },
        "Domy": {
            "Sprzedaż": {},
            "Wynajem": {},
        },
    },
    "Praca": {
        "UOP": {},
        "B2B": {},
    },
    "Motoryzacja": {},
    "Usługi": {},
    "Elektronika": {},
    "Zwierzęta": {
        "Psy": {},
        "Koty": {},
        "Świnki morskie": {},
    },
}


def add_initial_categories(apps, schema_editor):
    PostCategory = apps.get_model("posts", "PostCategory")

    def add_category(name: str, children: dict, parent: PostCategory = None):
        category = PostCategory.objects.create(name=name, parent=parent)
        for child_name, child_children in children.items():
            add_category(child_name, child_children, category)

    for category_name, category_children in INITIAL_CATEGORIES.items():
        add_category(category_name, category_children)


def remove_initial_cities(apps, schema_editor):
    PostCategory = apps.get_model("posts", "PostCategory")

    def remove_category(name: str, children: dict):
        for child_name, child_children in children.items():
            remove_category(child_name, child_children)
        PostCategory.objects.filter(name=name).delete()

    for category_name, category_children in INITIAL_CATEGORIES.items():
        remove_category(category_name, category_children)


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_initial_categories, remove_initial_cities)]
