# Generated by Django 5.1.4 on 2025-01-06 20:57

from django.db import migrations

INITIAL_CATEGORIES = {
    "properties": {
        "flats": {
            "sell": {},
            "rent": {},
        },
        "real-estate": {
            "sell": {},
            "rent": {},
        },
    },
    "job-offers": {
        "full-time": {},
        "part-time": {},
    },
    "cars": {},
    "services": {},
    "electronics": {},
    "animals": {
        "dogs": {},
        "cats": {},
        "guinea-pigs": {},
    },
}


def add_initial_categories(apps, schema_editor):
    PostCategory = apps.get_model("posts", "PostCategory")

    def add_category(name: str, children: dict, parent: PostCategory = None):
        category = PostCategory.objects.create(name=name, parent=parent)
        for child_name, child_children in children.items():
            add_category(child_name, child_children, category)

    for category_name, category_children in INITIAL_CATEGORIES.items():
        add_category(category_name, category_children)


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_initial_categories, migrations.RunPython.noop)
    ]
