# Generated by Django 5.1.4 on 2025-01-25 19:41

from django.db import migrations

INITIAL_POSTS = [
    {
        "city_id": 1,
        "category_id": 11,
        "author_id": 1,
        "title": "Honda Civic 2005 for Sale",
        "content": "Looking to sell my 2005 Honda Civic in excellent condition. Low mileage, no accidents, well-maintained. Contact me for more details and to schedule a viewing.",
        "created": "2025-01-01T10:00:00+00:00",
        "modified": "2025-01-01T12:00:00+00:00",
        "expiry": "2025-02-01T10:00:00+00:00",
    },
    {
        "city_id": 2,
        "category_id": 13,
        "author_id": 2,
        "title": "New Samsung A20s for Sale",
        "content": "Brand new Samsung A20s for sale. Unopened box, sealed and in original packaging. Perfect for anyone looking for an affordable smartphone with great features.",
        "created": "2025-01-15T08:30:00+00:00",
        "modified": "2025-01-15T09:00:00+00:00",
        "expiry": "2025-02-15T08:30:00+00:00",
    },
    {
        "city_id": 6,
        "category_id": 9,
        "author_id": 3,
        "title": "Sales Manager Job Opening in Gdansk",
        "content": "We are hiring a Sales Manager for our growing team in Gdansk. Ideal candidate should have 5+ years in sales and experience in managing a team. Competitive salary and benefits. Apply now!",
        "created": "2025-01-20T14:00:00+00:00",
        "modified": "2025-01-20T15:00:00+00:00",
        "expiry": "2025-02-20T14:00:00+00:00",
    },
    {
        "city_id": 4,
        "category_id": 11,
        "author_id": 4,
        "title": "Ford Focus 2010 for Sale - Great Condition",
        "content": "Selling my 2010 Ford Focus. It has been well-maintained and runs perfectly. New tires, fresh oil change, and recent inspection. DM me for more info or to schedule a test drive.",
        "created": "2025-01-22T11:00:00+00:00",
        "modified": "2025-01-22T12:00:00+00:00",
        "expiry": "2025-02-22T11:00:00+00:00",
    },
    {
        "city_id": 5,
        "category_id": 13,
        "author_id": 5,
        "title": "MacBook Pro 2020 for Sale - Excellent Condition",
        "content": "Selling my MacBook Pro 2020, 13-inch model. Comes with Apple warranty, original charger, and has been used sparingly. Perfect for work or school. Price negotiable. Contact me if interested.",
        "created": "2025-01-25T09:30:00+00:00",
        "modified": "2025-01-25T10:00:00+00:00",
        "expiry": "2025-02-25T09:30:00+00:00",
    },
    {
        "city_id": 1,
        "category_id": 9,
        "author_id": 1,
        "title": "Full-time Software Developer Position in Warsaw",
        "content": "Join our fast-growing tech company! We’re looking for a talented full-time software developer with experience in Python, Django, and front-end technologies. Great benefits and team atmosphere.",
        "created": "2025-01-03T09:00:00+00:00",
        "modified": "2025-01-03T09:30:00+00:00",
        "expiry": "2025-01-20T09:00:00+00:00",
    },
]


def add_initial_posts(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    for post in INITIAL_POSTS:
        Post.objects.create(**post)


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_add_initial_categories"),
        ("user_management", "0002_add_initial_users"),
    ]

    operations = [migrations.RunPython(add_initial_posts, migrations.RunPython.noop)]
