# Generated by Django 5.1.4 on 2025-02-06 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_add_initial_posts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
