# Generated by Django 5.2 on 2025-05-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiry',
            field=models.DateField(verbose_name='Expires at'),
        ),
    ]
