assert_lefthook_installed = true
rc = "$PWD/.lefthookrc"

[pre-commit]
parallel = true


[[pre-commit.jobs]]
name = "backend"
root = "backend/"
glob = "*.py"

[pre-commit.jobs.group]
piped = true

[[pre-commit.jobs.group.jobs]]
name = "lint backend"
run = "ruff check --fix {staged_files}"
stage_fixed = true

[[pre-commit.jobs.group.jobs]]
name = "format backend"
run = "ruff format {staged_files}"
stage_fixed = true


[[pre-commit.jobs]]
name = "frontend"
root = "frontend/"

[pre-commit.jobs.group]
piped = true

[[pre-commit.jobs.group.jobs]]
name = "lint frontend"
glob = "*.{html,ts}"
run = "pnpm lint"
stage_fixed = true

[[pre-commit.jobs.group.jobs]]
name = "format frontend"
glob = "*.{html,js,ts,json,md}"
run = "pnpm format"
stage_fixed = true
