assert_lefthook_installed = true
rc = "$PWD/.lefthookrc"

[pre-commit]
parallel = true


[[pre-commit.jobs]]
name = "backend"
root = "backend/"
glob = "*.py"
stage_fixed = true

[pre-commit.jobs.group]
piped = true

[[pre-commit.jobs.group.jobs]]
name = "lint backend"
run = "ruff check --fix {staged_files}"

[[pre-commit.jobs.group.jobs]]
name = "format backend"
run = "ruff format {staged_files}"


[[pre-commit.jobs]]
name = "frontend"
root = "frontend/"
glob = "*.{js,ts}"
stage_fixed = true

[pre-commit.jobs.group]
piped = true

[[pre-commit.jobs.group.jobs]]
name = "lint frontend"
run = "pnpm lint --lint-file-patterns {staged_files}"

[[pre-commit.jobs.group.jobs]]
name = "format frontend"
run = "pnpm format {staged_files}"
