# Generated by Django 5.1.4 on 2025-01-25 19:19
from django.db import migrations

INITIAL_USERS = [
    {
        "username": "alice",
        "email": "alice.lidell@example.com",
        "password": "zaq12wsx",
        "first_name": "Alice",
        "last_name": "Liddell",
    },
    {
        "username": "john",
        "email": "john.doe@example.com",
        "password": "zaq12wsx",
        "first_name": "John",
        "last_name": "Doe",
    },
    {
        "username": "maria",
        "email": "maria.smith@example.com",
        "password": "zaq12wsx",
        "first_name": "Maria",
        "last_name": "Smith",
    },
    {
        "username": "lucas",
        "email": "lucas.miller@example.com",
        "password": "zaq12wsx",
        "first_name": "Lucas",
        "last_name": "Miller",
    },
    {
        "username": "emily",
        "email": "emily.jones@example.com",
        "password": "zaq12wsx",
        "first_name": "Emily",
        "last_name": "Jones",
    },
]


def add_initial_users(apps, schema_editor):
    User = apps.get_model("user_management", "User")
    for user in INITIAL_USERS:
        User.objects.create_user(**user)


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_initial_users, migrations.RunPython.noop)]
