# Generated by Django 5.1.4 on 2025-01-06 19:01

from django.db import migrations

INITIAL_CITIES = [
    "Warszawa",
    "Kraków",
    "Łódź",
    "Wrocław",
    "Poznań",
    "Gdańsk",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Katowice",
    "Białystok",
    "Gdynia",
    "Częstochowa",
    "Radom",
    "Toruń",
    "Kielce",
    "Gliwice",
    "Zabrze",
    "Bytom",
    "Olsztyn",
    "Rzeszów",
    "Ruda Śląska",
    "Opole",
    "Tychy",
    "Dąbrowa Górnicza",
    "Elbląg",
    "Płock",
    "Nowy Sącz",
    "Koszalin",
    "Słupsk",
    "Jelenia Góra",
]


def add_initial_cities(apps, schema_editor):
    City = apps.get_model("cities", "City")
    for city_name in INITIAL_CITIES:
        City.objects.create(name=city_name)


def remove_initial_cities(apps, schema_editor):
    City = apps.get_model("cities", "City")
    City.objects.filter(name__in=INITIAL_CITIES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_initial_cities, remove_initial_cities)]
