# Generated by Django 5.1.4 on 2025-01-25 19:41

from datetime import timedelta
from random import choice

from django.db import migrations
from django.utils import timezone
from lorem import lorem


def get_all_ids(model):
    return list(model.objects.values_list("id", flat=True))


def gen_initial_posts(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    cities_ids = get_all_ids(apps.get_model("cities", "City"))
    categories_ids = get_all_ids(apps.get_model("posts", "PostCategory"))
    users_ids = get_all_ids(apps.get_model("user_management", "User"))
    expiry = timezone.now() + timedelta(days=30)
    for _ in range(100):
        Post.objects.create(
            city_id=choice(cities_ids),
            category_id=choice(categories_ids),
            author_id=choice(users_ids),
            title=lorem.get_sentence(),
            content=lorem.get_sentence(count=10),
            expiry=expiry,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_add_initial_categories"),
        ("user_management", "0002_add_initial_users"),
    ]

    operations = [migrations.RunPython(gen_initial_posts, migrations.RunPython.noop)]
